FROM cerberus:deps

COPY --chown=user1 . /home/opam/cerberus/
RUN eval `opam env` && \
  cd /home/opam/cerberus/ && \
  opam install -y --deps-only ./cerberus-lib.opam ./cn.opam && \
  make && \
  make install && \
  make install_cn
COPY --chown=user1 docker_entry_point.sh /home/user1/
RUN chmod +x docker_entry_point.sh
WORKDIR /data
ENTRYPOINT ["/home/user1/docker_entry_point.sh"]
